### PR TITLE
feat: Add `hypper docs` command, to generate markdown/man/bash command docs

### PR DESCRIPTION
**Pull request by viccuad**
This is lifted from Helm's `cmd/helm/docs.go`.
This will allow us to automate creation of cli docs, to put on the docs page.

Example:
```shell
$ mkdir docs/user/cli
$ hypper docs -dir docs/user/cli
$ tree docs/user/cli

docs/user/cli
├── hypper_install.md
├── hypper_lint.md
├── hypper_list.md
├── hypper.md
├── hypper_repo_add.md
├── hypper_repo_index.md
├── hypper_repo_list.md
├── hypper_repo.md
├── hypper_repo_remove.md
├── hypper_repo_update.md
├── hypper_search.md
├── hypper_search_repo.md
├── hypper_shared-dep_list.md
├── hypper_shared-dep.md
├── hypper_status.md
├── hypper_uninstall.md
├── hypper_upgrade.md
└── hypper_version.md
```

### CODE REVIEW

**Comment by viccuad** [comment]
Example, `docs/user/cli/hypper-lint.md`:


---


## hypper lint

examine a chart for possible issues

### Synopsis


This command takes a path to a chart and runs a series of tests to verify that
the chart is well-formed.

If the linter encounters things that will cause the chart to fail installation,
it will emit [ERROR] messages. If it encounters issues that break with convention
or recommendation, it will emit [WARNING] messages.


```
hypper lint PATH [flags]
```

### Options

```
  -h, --help                     help for lint
      --set stringArray          set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray     set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray   set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --strict                   fail on lint warnings
  -f, --values strings           specify values in a YAML file or a URL (can specify multiple)
      --with-subcharts           lint dependent charts
```

### Options inherited from parent commands

```
      --debug                       enable verbose output
      --kube-apiserver string       the address and the port for the Kubernetes API server
      --kube-as-group stringArray   group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --kube-as-user string         username to impersonate for the operation
      --kube-ca-file string         the certificate authority file for the Kubernetes API server connection
      --kube-context string         name of the kubeconfig context to use
      --kube-token string           bearer token used for authentication
      --kubeconfig string           path to the kubeconfig file
  -n, --namespace string            namespace scope for this request
      --no-colors                   disable colors
      --no-emojis                   disable emojis
      --registry-config string      path to the registry config file (default "/home/vic/.config/hypper/registry.json")
      --repository-cache string     path to the file containing cached repository indexes (default "/home/vic/.cache/hypper/repository")
      --repository-config string    path to the file containing repository names and URLs (default "/home/vic/.config/hypper/repositories.yaml")
```

### SEE ALSO

* [hypper](hypper.md)	 - A package manager built on Helm charts and Helm itself

###### Auto generated by spf13/cobra on 13-Apr-2021

**Comment by Itxaka** [comment]
N.I.C.E.

Missing go.sum changes though :P

**Comment by viccuad** [comment]
I really don't get the errors. Re-did the last commit, and I only get the already present `go.sum` changes (which seem unrelated to this PR). Here it works, with go1.15.9.

**Review by Itxaka — APPROVED** [review]

**Comment by viccuad** [comment]
thanks for the commit!

**Pull request merged**
